//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaimo_File_Server.Core.Language {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Kaimo_File_Server.Core.Language.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Web_Error_PrincipalNotSelected {
            get {
                return ResourceManager.GetString("Web_Error_PrincipalNotSelected", resourceCulture);
            }
        }
        
        public static string Web_Error_DuplicatePermissionEntry {
            get {
                return ResourceManager.GetString("Web_Error_DuplicatePermissionEntry", resourceCulture);
            }
        }
        
        public static string Web_Error_PermissionNotSelected {
            get {
                return ResourceManager.GetString("Web_Error_PermissionNotSelected", resourceCulture);
            }
        }
        
        public static string Context_Menu_Rename {
            get {
                return ResourceManager.GetString("Context_Menu_Rename", resourceCulture);
            }
        }
        
        public static string Context_Menu_Delete {
            get {
                return ResourceManager.GetString("Context_Menu_Delete", resourceCulture);
            }
        }
        
        public static string Web_Folder_Empty {
            get {
                return ResourceManager.GetString("Web_Folder_Empty", resourceCulture);
            }
        }
        
        public static string Web_Folder_Last_Access {
            get {
                return ResourceManager.GetString("Web_Folder_Last_Access", resourceCulture);
            }
        }
        
        public static string Web_Folder_Modified {
            get {
                return ResourceManager.GetString("Web_Folder_Modified", resourceCulture);
            }
        }
        
        public static string Web_Folder_Created {
            get {
                return ResourceManager.GetString("Web_Folder_Created", resourceCulture);
            }
        }
        
        public static string Web_Folder_Size {
            get {
                return ResourceManager.GetString("Web_Folder_Size", resourceCulture);
            }
        }
        
        public static string Web_Folder_Name {
            get {
                return ResourceManager.GetString("Web_Folder_Name", resourceCulture);
            }
        }
        
        public static string Web_Files {
            get {
                return ResourceManager.GetString("Web_Files", resourceCulture);
            }
        }
        
        public static string Web_Breadcrumb_Shares {
            get {
                return ResourceManager.GetString("Web_Breadcrumb_Shares", resourceCulture);
            }
        }
        
        public static string Web_Action_Open {
            get {
                return ResourceManager.GetString("Web_Action_Open", resourceCulture);
            }
        }
        
        public static string Web_Action_Rename {
            get {
                return ResourceManager.GetString("Web_Action_Rename", resourceCulture);
            }
        }
        
        public static string Web_Action_Delete {
            get {
                return ResourceManager.GetString("Web_Action_Delete", resourceCulture);
            }
        }
        
        public static string Web_Action_Permissions {
            get {
                return ResourceManager.GetString("Web_Action_Permissions", resourceCulture);
            }
        }
        
        public static string Web_Button_Cancel {
            get {
                return ResourceManager.GetString("Web_Button_Cancel", resourceCulture);
            }
        }
        
        public static string Web_Button_Create {
            get {
                return ResourceManager.GetString("Web_Button_Create", resourceCulture);
            }
        }
        
        public static string Web_Button_Close {
            get {
                return ResourceManager.GetString("Web_Button_Close", resourceCulture);
            }
        }
        
        public static string Web_Selection_None {
            get {
                return ResourceManager.GetString("Web_Selection_None", resourceCulture);
            }
        }
        
        public static string Web_Selection_Count {
            get {
                return ResourceManager.GetString("Web_Selection_Count", resourceCulture);
            }
        }
        
        public static string Web_CreateFolder_Title {
            get {
                return ResourceManager.GetString("Web_CreateFolder_Title", resourceCulture);
            }
        }
        
        public static string Web_CreateFolder_Placeholder {
            get {
                return ResourceManager.GetString("Web_CreateFolder_Placeholder", resourceCulture);
            }
        }
        
        public static string Web_ManagePermissions {
            get {
                return ResourceManager.GetString("Web_ManagePermissions", resourceCulture);
            }
        }
        
        public static string Web_DeleteConfirm_Title {
            get {
                return ResourceManager.GetString("Web_DeleteConfirm_Title", resourceCulture);
            }
        }
        
        public static string Web_DeleteConfirm_Single {
            get {
                return ResourceManager.GetString("Web_DeleteConfirm_Single", resourceCulture);
            }
        }
        
        public static string Web_DeleteConfirm_Multiple {
            get {
                return ResourceManager.GetString("Web_DeleteConfirm_Multiple", resourceCulture);
            }
        }
        
        public static string Web_DeleteConfirm_FolderWarning {
            get {
                return ResourceManager.GetString("Web_DeleteConfirm_FolderWarning", resourceCulture);
            }
        }
        
        public static string Web_DeleteConfirm_FoldersWarning {
            get {
                return ResourceManager.GetString("Web_DeleteConfirm_FoldersWarning", resourceCulture);
            }
        }
        
        public static string Web_Rename_Placeholder {
            get {
                return ResourceManager.GetString("Web_Rename_Placeholder", resourceCulture);
            }
        }
        
        public static string Web_Acl_ShareRoot {
            get {
                return ResourceManager.GetString("Web_Acl_ShareRoot", resourceCulture);
            }
        }
        
        public static string Web_Acl_PermissionsFor {
            get {
                return ResourceManager.GetString("Web_Acl_PermissionsFor", resourceCulture);
            }
        }
        
        public static string Web_Acl_RulesSingular {
            get {
                return ResourceManager.GetString("Web_Acl_RulesSingular", resourceCulture);
            }
        }
        
        public static string Web_Acl_RulesPlural {
            get {
                return ResourceManager.GetString("Web_Acl_RulesPlural", resourceCulture);
            }
        }
        
        public static string Web_Upload_Progress {
            get {
                return ResourceManager.GetString("Web_Upload_Progress", resourceCulture);
            }
        }
        
        public static string Web_Upload_Cancelled {
            get {
                return ResourceManager.GetString("Web_Upload_Cancelled", resourceCulture);
            }
        }
        
        public static string Web_Upload_TooLarge {
            get {
                return ResourceManager.GetString("Web_Upload_TooLarge", resourceCulture);
            }
        }
        
        public static string Web_Upload_Success {
            get {
                return ResourceManager.GetString("Web_Upload_Success", resourceCulture);
            }
        }
        
        public static string Web_Upload_Failed {
            get {
                return ResourceManager.GetString("Web_Upload_Failed", resourceCulture);
            }
        }
        
        public static string Web_Upload_PageLeft {
            get {
                return ResourceManager.GetString("Web_Upload_PageLeft", resourceCulture);
            }
        }
        
        public static string Web_Delete_Success {
            get {
                return ResourceManager.GetString("Web_Delete_Success", resourceCulture);
            }
        }
        
        public static string Web_Archive_DefaultName {
            get {
                return ResourceManager.GetString("Web_Archive_DefaultName", resourceCulture);
            }
        }
        
        public static string Web_Archive_Progress {
            get {
                return ResourceManager.GetString("Web_Archive_Progress", resourceCulture);
            }
        }
        
        public static string Web_Archive_Success {
            get {
                return ResourceManager.GetString("Web_Archive_Success", resourceCulture);
            }
        }
        
        public static string Web_Archive_Error {
            get {
                return ResourceManager.GetString("Web_Archive_Error", resourceCulture);
            }
        }
        
        public static string Web_Unzip_Progress {
            get {
                return ResourceManager.GetString("Web_Unzip_Progress", resourceCulture);
            }
        }
        
        public static string Web_Unzip_Success {
            get {
                return ResourceManager.GetString("Web_Unzip_Success", resourceCulture);
            }
        }
        
        public static string Web_Unzip_Error {
            get {
                return ResourceManager.GetString("Web_Unzip_Error", resourceCulture);
            }
        }
        
        public static string Context_Menu_Open {
            get {
                return ResourceManager.GetString("Context_Menu_Open", resourceCulture);
            }
        }
        
        public static string Context_Menu_Extract {
            get {
                return ResourceManager.GetString("Context_Menu_Extract", resourceCulture);
            }
        }
        
        public static string Context_Menu_CompressZip {
            get {
                return ResourceManager.GetString("Context_Menu_CompressZip", resourceCulture);
            }
        }
        
        public static string Context_Menu_CompressTarGz {
            get {
                return ResourceManager.GetString("Context_Menu_CompressTarGz", resourceCulture);
            }
        }
        
        public static string Context_Menu_Permissions {
            get {
                return ResourceManager.GetString("Context_Menu_Permissions", resourceCulture);
            }
        }
        
        public static string Context_Menu_SelectedItems {
            get {
                return ResourceManager.GetString("Context_Menu_SelectedItems", resourceCulture);
            }
        }
        
        public static string Context_Menu_General {
            get {
                return ResourceManager.GetString("Context_Menu_General", resourceCulture);
            }
        }
        
        public static string Context_Menu_NewFolder {
            get {
                return ResourceManager.GetString("Context_Menu_NewFolder", resourceCulture);
            }
        }
        
        public static string Context_Menu_Refresh {
            get {
                return ResourceManager.GetString("Context_Menu_Refresh", resourceCulture);
            }
        }
        
        public static string Web_ShareBrowser_PageTitle {
            get {
                return ResourceManager.GetString("Web_ShareBrowser_PageTitle", resourceCulture);
            }
        }
        
        public static string Web_ShareBrowser_Heading {
            get {
                return ResourceManager.GetString("Web_ShareBrowser_Heading", resourceCulture);
            }
        }
        
        public static string Web_ShareBrowser_CreateShare {
            get {
                return ResourceManager.GetString("Web_ShareBrowser_CreateShare", resourceCulture);
            }
        }
        
        public static string Web_ShareBrowser_ManageShares {
            get {
                return ResourceManager.GetString("Web_ShareBrowser_ManageShares", resourceCulture);
            }
        }
        
        public static string Web_ShareBrowser_Loading {
            get {
                return ResourceManager.GetString("Web_ShareBrowser_Loading", resourceCulture);
            }
        }
        
        public static string Web_ShareBrowser_Empty {
            get {
                return ResourceManager.GetString("Web_ShareBrowser_Empty", resourceCulture);
            }
        }
        
        public static string Web_File_Loading {
            get {
                return ResourceManager.GetString("Web_File_Loading", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Welcome {
            get {
                return ResourceManager.GetString("Web_ShareList_Welcome", resourceCulture);
            }
        }
        
        public static string Web_ShareList_CreateShare {
            get {
                return ResourceManager.GetString("Web_ShareList_CreateShare", resourceCulture);
            }
        }
        
        public static string Web_ShareList_CreateTitle {
            get {
                return ResourceManager.GetString("Web_ShareList_CreateTitle", resourceCulture);
            }
        }
        
        public static string Web_ShareList_CreatePlaceholder {
            get {
                return ResourceManager.GetString("Web_ShareList_CreatePlaceholder", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Label_Name {
            get {
                return ResourceManager.GetString("Web_ShareList_Label_Name", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Label_Path {
            get {
                return ResourceManager.GetString("Web_ShareList_Label_Path", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Label_Status {
            get {
                return ResourceManager.GetString("Web_ShareList_Label_Status", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Label_RecycleBin {
            get {
                return ResourceManager.GetString("Web_ShareList_Label_RecycleBin", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Label_Users {
            get {
                return ResourceManager.GetString("Web_ShareList_Label_Users", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Label_Groups {
            get {
                return ResourceManager.GetString("Web_ShareList_Label_Groups", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Status_Active {
            get {
                return ResourceManager.GetString("Web_ShareList_Status_Active", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Status_Disabled {
            get {
                return ResourceManager.GetString("Web_ShareList_Status_Disabled", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Action_Enable {
            get {
                return ResourceManager.GetString("Web_ShareList_Action_Enable", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Action_Disable {
            get {
                return ResourceManager.GetString("Web_ShareList_Action_Disable", resourceCulture);
            }
        }
        
        public static string Web_ShareList_DetailSubtitle {
            get {
                return ResourceManager.GetString("Web_ShareList_DetailSubtitle", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Tab_General {
            get {
                return ResourceManager.GetString("Web_ShareList_Tab_General", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Tab_Visibility {
            get {
                return ResourceManager.GetString("Web_ShareList_Tab_Visibility", resourceCulture);
            }
        }
        
        public static string Web_ShareList_DeleteShare {
            get {
                return ResourceManager.GetString("Web_ShareList_DeleteShare", resourceCulture);
            }
        }
        
        public static string Web_ShareList_DeleteConfirm {
            get {
                return ResourceManager.GetString("Web_ShareList_DeleteConfirm", resourceCulture);
            }
        }
        
        public static string Web_ShareList_DeletePermanently {
            get {
                return ResourceManager.GetString("Web_ShareList_DeletePermanently", resourceCulture);
            }
        }
        
        public static string Web_ShareList_VisibilityDescription {
            get {
                return ResourceManager.GetString("Web_ShareList_VisibilityDescription", resourceCulture);
            }
        }
        
        public static string Web_ShareList_NoUsers {
            get {
                return ResourceManager.GetString("Web_ShareList_NoUsers", resourceCulture);
            }
        }
        
        public static string Web_ShareList_NoUsersAvailable {
            get {
                return ResourceManager.GetString("Web_ShareList_NoUsersAvailable", resourceCulture);
            }
        }
        
        public static string Web_ShareList_NoGroups {
            get {
                return ResourceManager.GetString("Web_ShareList_NoGroups", resourceCulture);
            }
        }
        
        public static string Web_ShareList_NoGroupsAvailable {
            get {
                return ResourceManager.GetString("Web_ShareList_NoGroupsAvailable", resourceCulture);
            }
        }
        
        public static string Web_ShareList_VisibleToAll {
            get {
                return ResourceManager.GetString("Web_ShareList_VisibleToAll", resourceCulture);
            }
        }
        
        public static string Web_ShareList_AclDescription {
            get {
                return ResourceManager.GetString("Web_ShareList_AclDescription", resourceCulture);
            }
        }
        
        public static string Web_Nav_Shares {
            get {
                return ResourceManager.GetString("Web_Nav_Shares", resourceCulture);
            }
        }
        
        public static string Web_Nav_Users {
            get {
                return ResourceManager.GetString("Web_Nav_Users", resourceCulture);
            }
        }
        
        public static string Web_Nav_Departments {
            get {
                return ResourceManager.GetString("Web_Nav_Departments", resourceCulture);
            }
        }
        
        public static string Web_Nav_BrowseFiles {
            get {
                return ResourceManager.GetString("Web_Nav_BrowseFiles", resourceCulture);
            }
        }
        
        public static string Web_Nav_ToggleTheme {
            get {
                return ResourceManager.GetString("Web_Nav_ToggleTheme", resourceCulture);
            }
        }
        
        public static string Web_Nav_Logout {
            get {
                return ResourceManager.GetString("Web_Nav_Logout", resourceCulture);
            }
        }
    }
}
