//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaimo_File_Server.Core.Language {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Kaimo_File_Server.Core.Language.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Web_Error_PrincipalNotSelected {
            get {
                return ResourceManager.GetString("Web_Error_PrincipalNotSelected", resourceCulture);
            }
        }
        
        public static string Web_Error_DuplicatePermissionEntry {
            get {
                return ResourceManager.GetString("Web_Error_DuplicatePermissionEntry", resourceCulture);
            }
        }
        
        public static string Web_Error_PermissionNotSelected {
            get {
                return ResourceManager.GetString("Web_Error_PermissionNotSelected", resourceCulture);
            }
        }
        
        public static string Context_Menu_Rename {
            get {
                return ResourceManager.GetString("Context_Menu_Rename", resourceCulture);
            }
        }
        
        public static string Context_Menu_Delete {
            get {
                return ResourceManager.GetString("Context_Menu_Delete", resourceCulture);
            }
        }
        
        public static string Web_Folder_Empty {
            get {
                return ResourceManager.GetString("Web_Folder_Empty", resourceCulture);
            }
        }
        
        public static string Web_Folder_Last_Access {
            get {
                return ResourceManager.GetString("Web_Folder_Last_Access", resourceCulture);
            }
        }
        
        public static string Web_Folder_Modified {
            get {
                return ResourceManager.GetString("Web_Folder_Modified", resourceCulture);
            }
        }
        
        public static string Web_Folder_Created {
            get {
                return ResourceManager.GetString("Web_Folder_Created", resourceCulture);
            }
        }
        
        public static string Web_Folder_Size {
            get {
                return ResourceManager.GetString("Web_Folder_Size", resourceCulture);
            }
        }
        
        public static string Web_Folder_Name {
            get {
                return ResourceManager.GetString("Web_Folder_Name", resourceCulture);
            }
        }
        
        public static string Web_Files {
            get {
                return ResourceManager.GetString("Web_Files", resourceCulture);
            }
        }
        
        public static string Web_Breadcrumb_Shares {
            get {
                return ResourceManager.GetString("Web_Breadcrumb_Shares", resourceCulture);
            }
        }
        
        public static string Web_Action_Open {
            get {
                return ResourceManager.GetString("Web_Action_Open", resourceCulture);
            }
        }
        
        public static string Web_Action_Rename {
            get {
                return ResourceManager.GetString("Web_Action_Rename", resourceCulture);
            }
        }
        
        public static string Web_Action_Delete {
            get {
                return ResourceManager.GetString("Web_Action_Delete", resourceCulture);
            }
        }
        
        public static string Web_Action_Permissions {
            get {
                return ResourceManager.GetString("Web_Action_Permissions", resourceCulture);
            }
        }
        
        public static string Web_Button_Cancel {
            get {
                return ResourceManager.GetString("Web_Button_Cancel", resourceCulture);
            }
        }
        
        public static string Web_Button_Create {
            get {
                return ResourceManager.GetString("Web_Button_Create", resourceCulture);
            }
        }
        
        public static string Web_Button_Close {
            get {
                return ResourceManager.GetString("Web_Button_Close", resourceCulture);
            }
        }
        
        public static string Web_Selection_None {
            get {
                return ResourceManager.GetString("Web_Selection_None", resourceCulture);
            }
        }
        
        public static string Web_Selection_Count {
            get {
                return ResourceManager.GetString("Web_Selection_Count", resourceCulture);
            }
        }
        
        public static string Web_CreateFolder_Title {
            get {
                return ResourceManager.GetString("Web_CreateFolder_Title", resourceCulture);
            }
        }
        
        public static string Web_CreateFolder_Placeholder {
            get {
                return ResourceManager.GetString("Web_CreateFolder_Placeholder", resourceCulture);
            }
        }
        
        public static string Web_ManagePermissions {
            get {
                return ResourceManager.GetString("Web_ManagePermissions", resourceCulture);
            }
        }
        
        public static string Web_DeleteConfirm_Title {
            get {
                return ResourceManager.GetString("Web_DeleteConfirm_Title", resourceCulture);
            }
        }
        
        public static string Web_DeleteConfirm_Single {
            get {
                return ResourceManager.GetString("Web_DeleteConfirm_Single", resourceCulture);
            }
        }
        
        public static string Web_DeleteConfirm_Multiple {
            get {
                return ResourceManager.GetString("Web_DeleteConfirm_Multiple", resourceCulture);
            }
        }
        
        public static string Web_DeleteConfirm_FolderWarning {
            get {
                return ResourceManager.GetString("Web_DeleteConfirm_FolderWarning", resourceCulture);
            }
        }
        
        public static string Web_DeleteConfirm_FoldersWarning {
            get {
                return ResourceManager.GetString("Web_DeleteConfirm_FoldersWarning", resourceCulture);
            }
        }
        
        public static string Web_Rename_Placeholder {
            get {
                return ResourceManager.GetString("Web_Rename_Placeholder", resourceCulture);
            }
        }
        
        public static string Web_Acl_ShareRoot {
            get {
                return ResourceManager.GetString("Web_Acl_ShareRoot", resourceCulture);
            }
        }
        
        public static string Web_Acl_PermissionsFor {
            get {
                return ResourceManager.GetString("Web_Acl_PermissionsFor", resourceCulture);
            }
        }
        
        public static string Web_Acl_RulesSingular {
            get {
                return ResourceManager.GetString("Web_Acl_RulesSingular", resourceCulture);
            }
        }
        
        public static string Web_Acl_RulesPlural {
            get {
                return ResourceManager.GetString("Web_Acl_RulesPlural", resourceCulture);
            }
        }
        
        public static string Web_Upload_Progress {
            get {
                return ResourceManager.GetString("Web_Upload_Progress", resourceCulture);
            }
        }
        
        public static string Web_Upload_Cancelled {
            get {
                return ResourceManager.GetString("Web_Upload_Cancelled", resourceCulture);
            }
        }
        
        public static string Web_Upload_TooLarge {
            get {
                return ResourceManager.GetString("Web_Upload_TooLarge", resourceCulture);
            }
        }
        
        public static string Web_Upload_Success {
            get {
                return ResourceManager.GetString("Web_Upload_Success", resourceCulture);
            }
        }
        
        public static string Web_Upload_Failed {
            get {
                return ResourceManager.GetString("Web_Upload_Failed", resourceCulture);
            }
        }
        
        public static string Web_Upload_PageLeft {
            get {
                return ResourceManager.GetString("Web_Upload_PageLeft", resourceCulture);
            }
        }
        
        public static string Web_Delete_Success {
            get {
                return ResourceManager.GetString("Web_Delete_Success", resourceCulture);
            }
        }
        
        public static string Web_Archive_DefaultName {
            get {
                return ResourceManager.GetString("Web_Archive_DefaultName", resourceCulture);
            }
        }
        
        public static string Web_Archive_Progress {
            get {
                return ResourceManager.GetString("Web_Archive_Progress", resourceCulture);
            }
        }
        
        public static string Web_Archive_Success {
            get {
                return ResourceManager.GetString("Web_Archive_Success", resourceCulture);
            }
        }
        
        public static string Web_Archive_Error {
            get {
                return ResourceManager.GetString("Web_Archive_Error", resourceCulture);
            }
        }
        
        public static string Web_Unzip_Progress {
            get {
                return ResourceManager.GetString("Web_Unzip_Progress", resourceCulture);
            }
        }
        
        public static string Web_Unzip_Success {
            get {
                return ResourceManager.GetString("Web_Unzip_Success", resourceCulture);
            }
        }
        
        public static string Web_Unzip_Error {
            get {
                return ResourceManager.GetString("Web_Unzip_Error", resourceCulture);
            }
        }
        
        public static string Context_Menu_Open {
            get {
                return ResourceManager.GetString("Context_Menu_Open", resourceCulture);
            }
        }
        
        public static string Context_Menu_Extract {
            get {
                return ResourceManager.GetString("Context_Menu_Extract", resourceCulture);
            }
        }
        
        public static string Context_Menu_CompressZip {
            get {
                return ResourceManager.GetString("Context_Menu_CompressZip", resourceCulture);
            }
        }
        
        public static string Context_Menu_CompressTarGz {
            get {
                return ResourceManager.GetString("Context_Menu_CompressTarGz", resourceCulture);
            }
        }
        
        public static string Context_Menu_Permissions {
            get {
                return ResourceManager.GetString("Context_Menu_Permissions", resourceCulture);
            }
        }
        
        public static string Context_Menu_SelectedItems {
            get {
                return ResourceManager.GetString("Context_Menu_SelectedItems", resourceCulture);
            }
        }
        
        public static string Context_Menu_General {
            get {
                return ResourceManager.GetString("Context_Menu_General", resourceCulture);
            }
        }
        
        public static string Context_Menu_NewFolder {
            get {
                return ResourceManager.GetString("Context_Menu_NewFolder", resourceCulture);
            }
        }
        
        public static string Context_Menu_Refresh {
            get {
                return ResourceManager.GetString("Context_Menu_Refresh", resourceCulture);
            }
        }
        
        public static string Web_ShareBrowser_PageTitle {
            get {
                return ResourceManager.GetString("Web_ShareBrowser_PageTitle", resourceCulture);
            }
        }
        
        public static string Web_ShareBrowser_Heading {
            get {
                return ResourceManager.GetString("Web_ShareBrowser_Heading", resourceCulture);
            }
        }
        
        public static string Web_ShareBrowser_CreateShare {
            get {
                return ResourceManager.GetString("Web_ShareBrowser_CreateShare", resourceCulture);
            }
        }
        
        public static string Web_ShareBrowser_ManageShares {
            get {
                return ResourceManager.GetString("Web_ShareBrowser_ManageShares", resourceCulture);
            }
        }
        
        public static string Web_ShareBrowser_Loading {
            get {
                return ResourceManager.GetString("Web_ShareBrowser_Loading", resourceCulture);
            }
        }
        
        public static string Web_ShareBrowser_Empty {
            get {
                return ResourceManager.GetString("Web_ShareBrowser_Empty", resourceCulture);
            }
        }
        
        public static string Web_File_Loading {
            get {
                return ResourceManager.GetString("Web_File_Loading", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Welcome {
            get {
                return ResourceManager.GetString("Web_ShareList_Welcome", resourceCulture);
            }
        }
        
        public static string Web_ShareList_CreateShare {
            get {
                return ResourceManager.GetString("Web_ShareList_CreateShare", resourceCulture);
            }
        }
        
        public static string Web_ShareList_CreateTitle {
            get {
                return ResourceManager.GetString("Web_ShareList_CreateTitle", resourceCulture);
            }
        }
        
        public static string Web_ShareList_CreatePlaceholder {
            get {
                return ResourceManager.GetString("Web_ShareList_CreatePlaceholder", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Label_Name {
            get {
                return ResourceManager.GetString("Web_ShareList_Label_Name", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Label_Path {
            get {
                return ResourceManager.GetString("Web_ShareList_Label_Path", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Label_Status {
            get {
                return ResourceManager.GetString("Web_ShareList_Label_Status", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Label_RecycleBin {
            get {
                return ResourceManager.GetString("Web_ShareList_Label_RecycleBin", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Label_Users {
            get {
                return ResourceManager.GetString("Web_ShareList_Label_Users", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Label_Groups {
            get {
                return ResourceManager.GetString("Web_ShareList_Label_Groups", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Status_Active {
            get {
                return ResourceManager.GetString("Web_ShareList_Status_Active", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Status_Disabled {
            get {
                return ResourceManager.GetString("Web_ShareList_Status_Disabled", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Action_Enable {
            get {
                return ResourceManager.GetString("Web_ShareList_Action_Enable", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Action_Disable {
            get {
                return ResourceManager.GetString("Web_ShareList_Action_Disable", resourceCulture);
            }
        }
        
        public static string Web_ShareList_DetailSubtitle {
            get {
                return ResourceManager.GetString("Web_ShareList_DetailSubtitle", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Tab_General {
            get {
                return ResourceManager.GetString("Web_ShareList_Tab_General", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Tab_Visibility {
            get {
                return ResourceManager.GetString("Web_ShareList_Tab_Visibility", resourceCulture);
            }
        }
        
        public static string Web_ShareList_DeleteShare {
            get {
                return ResourceManager.GetString("Web_ShareList_DeleteShare", resourceCulture);
            }
        }
        
        public static string Web_ShareList_DeleteConfirm {
            get {
                return ResourceManager.GetString("Web_ShareList_DeleteConfirm", resourceCulture);
            }
        }
        
        public static string Web_ShareList_DeletePermanently {
            get {
                return ResourceManager.GetString("Web_ShareList_DeletePermanently", resourceCulture);
            }
        }
        
        public static string Web_ShareList_VisibilityDescription {
            get {
                return ResourceManager.GetString("Web_ShareList_VisibilityDescription", resourceCulture);
            }
        }
        
        public static string Web_ShareList_NoUsers {
            get {
                return ResourceManager.GetString("Web_ShareList_NoUsers", resourceCulture);
            }
        }
        
        public static string Web_ShareList_NoUsersAvailable {
            get {
                return ResourceManager.GetString("Web_ShareList_NoUsersAvailable", resourceCulture);
            }
        }
        
        public static string Web_ShareList_NoGroups {
            get {
                return ResourceManager.GetString("Web_ShareList_NoGroups", resourceCulture);
            }
        }
        
        public static string Web_ShareList_NoGroupsAvailable {
            get {
                return ResourceManager.GetString("Web_ShareList_NoGroupsAvailable", resourceCulture);
            }
        }
        
        public static string Web_ShareList_VisibleToAll {
            get {
                return ResourceManager.GetString("Web_ShareList_VisibleToAll", resourceCulture);
            }
        }
        
        public static string Web_ShareList_AclDescription {
            get {
                return ResourceManager.GetString("Web_ShareList_AclDescription", resourceCulture);
            }
        }
        
        public static string Web_Nav_Shares {
            get {
                return ResourceManager.GetString("Web_Nav_Shares", resourceCulture);
            }
        }
        
        public static string Web_Nav_Users {
            get {
                return ResourceManager.GetString("Web_Nav_Users", resourceCulture);
            }
        }
        
        public static string Web_Nav_Departments {
            get {
                return ResourceManager.GetString("Web_Nav_Departments", resourceCulture);
            }
        }
        
        public static string Web_Nav_BrowseFiles {
            get {
                return ResourceManager.GetString("Web_Nav_BrowseFiles", resourceCulture);
            }
        }
        
        public static string Web_Nav_ToggleTheme {
            get {
                return ResourceManager.GetString("Web_Nav_ToggleTheme", resourceCulture);
            }
        }
        
        public static string Web_Nav_Logout {
            get {
                return ResourceManager.GetString("Web_Nav_Logout", resourceCulture);
            }
        }
        
        public static string Web_Nav_Settings {
            get {
                return ResourceManager.GetString("Web_Nav_Settings", resourceCulture);
            }
        }
        
        public static string Web_ShareList_Tab_ACL {
            get {
                return ResourceManager.GetString("Web_ShareList_Tab_ACL", resourceCulture);
            }
        }
        
        public static string Web_ShareList_VisibilityHeader {
            get {
                return ResourceManager.GetString("Web_ShareList_VisibilityHeader", resourceCulture);
            }
        }
        
        public static string Web_Acl_LoadingPermissions {
            get {
                return ResourceManager.GetString("Web_Acl_LoadingPermissions", resourceCulture);
            }
        }
        
        public static string Web_Acl_Directly {
            get {
                return ResourceManager.GetString("Web_Acl_Directly", resourceCulture);
            }
        }
        
        public static string Web_Acl_Inheritance {
            get {
                return ResourceManager.GetString("Web_Acl_Inheritance", resourceCulture);
            }
        }
        
        public static string Web_Acl_EmptyHint {
            get {
                return ResourceManager.GetString("Web_Acl_EmptyHint", resourceCulture);
            }
        }
        
        public static string Web_Acl_AddPermission {
            get {
                return ResourceManager.GetString("Web_Acl_AddPermission", resourceCulture);
            }
        }
        
        public static string Web_Acl_Button_User {
            get {
                return ResourceManager.GetString("Web_Acl_Button_User", resourceCulture);
            }
        }
        
        public static string Web_Acl_Button_Group {
            get {
                return ResourceManager.GetString("Web_Acl_Button_Group", resourceCulture);
            }
        }
        
        public static string Web_Acl_Button_Role {
            get {
                return ResourceManager.GetString("Web_Acl_Button_Role", resourceCulture);
            }
        }
        
        public static string Web_Acl_Action {
            get {
                return ResourceManager.GetString("Web_Acl_Action", resourceCulture);
            }
        }
        
        public static string Web_Acl_Permission_Read {
            get {
                return ResourceManager.GetString("Web_Acl_Permission_Read", resourceCulture);
            }
        }
        
        public static string Web_Acl_Permission_Write {
            get {
                return ResourceManager.GetString("Web_Acl_Permission_Write", resourceCulture);
            }
        }
        
        public static string Web_Acl_Permission_Admin {
            get {
                return ResourceManager.GetString("Web_Acl_Permission_Admin", resourceCulture);
            }
        }
        
        public static string Web_Acl_Permission_FullAccess {
            get {
                return ResourceManager.GetString("Web_Acl_Permission_FullAccess", resourceCulture);
            }
        }
        
        public static string Web_Acl_Inherited {
            get {
                return ResourceManager.GetString("Web_Acl_Inherited", resourceCulture);
            }
        }
        
        public static string Web_Acl_Allow {
            get {
                return ResourceManager.GetString("Web_Acl_Allow", resourceCulture);
            }
        }
        
        public static string Web_Acl_Deny {
            get {
                return ResourceManager.GetString("Web_Acl_Deny", resourceCulture);
            }
        }
        
        public static string Web_Acl_InheritedFrom {
            get {
                return ResourceManager.GetString("Web_Acl_InheritedFrom", resourceCulture);
            }
        }
        
        public static string Web_Acl_Edit {
            get {
                return ResourceManager.GetString("Web_Acl_Edit", resourceCulture);
            }
        }
        
        public static string Web_Acl_Remove {
            get {
                return ResourceManager.GetString("Web_Acl_Remove", resourceCulture);
            }
        }
        
        public static string Web_Acl_Type {
            get {
                return ResourceManager.GetString("Web_Acl_Type", resourceCulture);
            }
        }
        
        public static string Web_Acl_SelectPlaceholder {
            get {
                return ResourceManager.GetString("Web_Acl_SelectPlaceholder", resourceCulture);
            }
        }
        
        public static string Web_Acl_QuickSelect {
            get {
                return ResourceManager.GetString("Web_Acl_QuickSelect", resourceCulture);
            }
        }
        
        public static string Web_Acl_DetailPermissions {
            get {
                return ResourceManager.GetString("Web_Acl_DetailPermissions", resourceCulture);
            }
        }
        
        public static string Web_Acl_None {
            get {
                return ResourceManager.GetString("Web_Acl_None", resourceCulture);
            }
        }
        
        public static string Web_Acl_Button_Add {
            get {
                return ResourceManager.GetString("Web_Acl_Button_Add", resourceCulture);
            }
        }
        
        public static string Web_Acl_Button_Save {
            get {
                return ResourceManager.GetString("Web_Acl_Button_Save", resourceCulture);
            }
        }
        
        public static string Web_Acl_Button_Cancel {
            get {
                return ResourceManager.GetString("Web_Acl_Button_Cancel", resourceCulture);
            }
        }
        
        public static string Web_Acl_Perm_TraverseExecute {
            get {
                return ResourceManager.GetString("Web_Acl_Perm_TraverseExecute", resourceCulture);
            }
        }
        
        public static string Web_Acl_Perm_ListReadData {
            get {
                return ResourceManager.GetString("Web_Acl_Perm_ListReadData", resourceCulture);
            }
        }
        
        public static string Web_Acl_Perm_ReadAttributes {
            get {
                return ResourceManager.GetString("Web_Acl_Perm_ReadAttributes", resourceCulture);
            }
        }
        
        public static string Web_Acl_Perm_ReadExtAttributes {
            get {
                return ResourceManager.GetString("Web_Acl_Perm_ReadExtAttributes", resourceCulture);
            }
        }
        
        public static string Web_Acl_Perm_ReadPermissions {
            get {
                return ResourceManager.GetString("Web_Acl_Perm_ReadPermissions", resourceCulture);
            }
        }
        
        public static string Web_Acl_Perm_CreateWriteData {
            get {
                return ResourceManager.GetString("Web_Acl_Perm_CreateWriteData", resourceCulture);
            }
        }
        
        public static string Web_Acl_Perm_CreateAppendData {
            get {
                return ResourceManager.GetString("Web_Acl_Perm_CreateAppendData", resourceCulture);
            }
        }
        
        public static string Web_Acl_Perm_WriteAttributes {
            get {
                return ResourceManager.GetString("Web_Acl_Perm_WriteAttributes", resourceCulture);
            }
        }
        
        public static string Web_Acl_Perm_WriteExtAttributes {
            get {
                return ResourceManager.GetString("Web_Acl_Perm_WriteExtAttributes", resourceCulture);
            }
        }
        
        public static string Web_Acl_Perm_DeleteSubItems {
            get {
                return ResourceManager.GetString("Web_Acl_Perm_DeleteSubItems", resourceCulture);
            }
        }
        
        public static string Web_Acl_Perm_Delete {
            get {
                return ResourceManager.GetString("Web_Acl_Perm_Delete", resourceCulture);
            }
        }
        
        public static string Web_Acl_Perm_ChangePermissions {
            get {
                return ResourceManager.GetString("Web_Acl_Perm_ChangePermissions", resourceCulture);
            }
        }
        
        public static string Web_Acl_Perm_TakeOwnership {
            get {
                return ResourceManager.GetString("Web_Acl_Perm_TakeOwnership", resourceCulture);
            }
        }
        
        public static string Web_Acl_Inherit_ThisFolder {
            get {
                return ResourceManager.GetString("Web_Acl_Inherit_ThisFolder", resourceCulture);
            }
        }
        
        public static string Web_Acl_Inherit_SubFolders {
            get {
                return ResourceManager.GetString("Web_Acl_Inherit_SubFolders", resourceCulture);
            }
        }
        
        public static string Web_Acl_Inherit_Files {
            get {
                return ResourceManager.GetString("Web_Acl_Inherit_Files", resourceCulture);
            }
        }
        
        public static string Web_Acl_Inherit_AllDescendants {
            get {
                return ResourceManager.GetString("Web_Acl_Inherit_AllDescendants", resourceCulture);
            }
        }
        
        public static string Web_Acl_Inherit_Everything {
            get {
                return ResourceManager.GetString("Web_Acl_Inherit_Everything", resourceCulture);
            }
        }
        
        public static string Web_Acl_Inherit_ThisOnly {
            get {
                return ResourceManager.GetString("Web_Acl_Inherit_ThisOnly", resourceCulture);
            }
        }
        
        public static string Web_Acl_Inherit_ThisAndDirect {
            get {
                return ResourceManager.GetString("Web_Acl_Inherit_ThisAndDirect", resourceCulture);
            }
        }
        
        public static string Web_Acl_Error_NoPath {
            get {
                return ResourceManager.GetString("Web_Acl_Error_NoPath", resourceCulture);
            }
        }
        
        public static string Web_Acl_Error_NoShareId {
            get {
                return ResourceManager.GetString("Web_Acl_Error_NoShareId", resourceCulture);
            }
        }
        
        public static string Web_Acl_Error_LoadFailed {
            get {
                return ResourceManager.GetString("Web_Acl_Error_LoadFailed", resourceCulture);
            }
        }
        
        public static string Web_Acl_Error_Exception {
            get {
                return ResourceManager.GetString("Web_Acl_Error_Exception", resourceCulture);
            }
        }
        
        public static string Web_Search_Placeholder {
            get {
                return ResourceManager.GetString("Web_Search_Placeholder", resourceCulture);
            }
        }
        
        public static string Web_Search_Searching {
            get {
                return ResourceManager.GetString("Web_Search_Searching", resourceCulture);
            }
        }
        
        public static string Web_Search_NoResults {
            get {
                return ResourceManager.GetString("Web_Search_NoResults", resourceCulture);
            }
        }
        
        public static string Web_Login_Failed {
            get {
                return ResourceManager.GetString("Web_Login_Failed", resourceCulture);
            }
        }
        
        public static string Web_Login_InvalidCredentials {
            get {
                return ResourceManager.GetString("Web_Login_InvalidCredentials", resourceCulture);
            }
        }
        
        public static string Web_Login_CredentialsRequired {
            get {
                return ResourceManager.GetString("Web_Login_CredentialsRequired", resourceCulture);
            }
        }
        
        public static string Web_Login_AccountDisabled {
            get {
                return ResourceManager.GetString("Web_Login_AccountDisabled", resourceCulture);
            }
        }

        public static string Web_Login_TooManyAttempts {
            get {
                return ResourceManager.GetString("Web_Login_TooManyAttempts", resourceCulture);
            }
        }
        
        public static string Web_Error_NotAuthenticated {
            get {
                return ResourceManager.GetString("Web_Error_NotAuthenticated", resourceCulture);
            }
        }
        
        public static string Web_Error_NotLoggedIn {
            get {
                return ResourceManager.GetString("Web_Error_NotLoggedIn", resourceCulture);
            }
        }
        
        public static string Web_Error_NoPermission {
            get {
                return ResourceManager.GetString("Web_Error_NoPermission", resourceCulture);
            }
        }
        
        public static string Web_Error_AccessDenied {
            get {
                return ResourceManager.GetString("Web_Error_AccessDenied", resourceCulture);
            }
        }
        
        public static string Web_Error_NoManagementPermission {
            get {
                return ResourceManager.GetString("Web_Error_NoManagementPermission", resourceCulture);
            }
        }
        
        public static string Web_Error_InvalidPath {
            get {
                return ResourceManager.GetString("Web_Error_InvalidPath", resourceCulture);
            }
        }
        
        public static string Web_Folder_NameRequired {
            get {
                return ResourceManager.GetString("Web_Folder_NameRequired", resourceCulture);
            }
        }
        
        public static string Web_Rename_NameRequired {
            get {
                return ResourceManager.GetString("Web_Rename_NameRequired", resourceCulture);
            }
        }
        
        public static string Web_Rename_Unchanged {
            get {
                return ResourceManager.GetString("Web_Rename_Unchanged", resourceCulture);
            }
        }
        
        public static string Web_FileName_Missing {
            get {
                return ResourceManager.GetString("Web_FileName_Missing", resourceCulture);
            }
        }
        
        public static string Web_Name_InvalidChars {
            get {
                return ResourceManager.GetString("Web_Name_InvalidChars", resourceCulture);
            }
        }
        
        public static string Web_FileName_InvalidChars {
            get {
                return ResourceManager.GetString("Web_FileName_InvalidChars", resourceCulture);
            }
        }
        
        public static string Web_Error_FileOrFolderNotFound {
            get {
                return ResourceManager.GetString("Web_Error_FileOrFolderNotFound", resourceCulture);
            }
        }
        
        public static string Web_Error_ItemExists {
            get {
                return ResourceManager.GetString("Web_Error_ItemExists", resourceCulture);
            }
        }
        
        public static string Web_Error_FolderExists {
            get {
                return ResourceManager.GetString("Web_Error_FolderExists", resourceCulture);
            }
        }
        
        public static string Web_Error_FileExists {
            get {
                return ResourceManager.GetString("Web_Error_FileExists", resourceCulture);
            }
        }
        
        public static string Web_Error_NotValidZip {
            get {
                return ResourceManager.GetString("Web_Error_NotValidZip", resourceCulture);
            }
        }
        
        public static string Web_Error_CreateFolderFailed {
            get {
                return ResourceManager.GetString("Web_Error_CreateFolderFailed", resourceCulture);
            }
        }
        
        public static string Web_Error_DeleteFailed {
            get {
                return ResourceManager.GetString("Web_Error_DeleteFailed", resourceCulture);
            }
        }
        
        public static string Web_Error_RenameFailed {
            get {
                return ResourceManager.GetString("Web_Error_RenameFailed", resourceCulture);
            }
        }
        
        public static string Web_Error_RenameFailedCheckLogs {
            get {
                return ResourceManager.GetString("Web_Error_RenameFailedCheckLogs", resourceCulture);
            }
        }
        
        public static string Web_Error_UploadFailed {
            get {
                return ResourceManager.GetString("Web_Error_UploadFailed", resourceCulture);
            }
        }
        
        public static string Web_Error_ArchiveFailed {
            get {
                return ResourceManager.GetString("Web_Error_ArchiveFailed", resourceCulture);
            }
        }
        
        public static string Web_Error_ExtractFailed {
            get {
                return ResourceManager.GetString("Web_Error_ExtractFailed", resourceCulture);
            }
        }
        
        public static string Web_Upload_Aborted {
            get {
                return ResourceManager.GetString("Web_Upload_Aborted", resourceCulture);
            }
        }
        
        public static string Web_Error_ShareInUse {
            get {
                return ResourceManager.GetString("Web_Error_ShareInUse", resourceCulture);
            }
        }
        
        public static string Web_Error_ShareDisabled {
            get {
                return ResourceManager.GetString("Web_Error_ShareDisabled", resourceCulture);
            }
        }
        
        public static string Web_Error_ShareNotFound {
            get {
                return ResourceManager.GetString("Web_Error_ShareNotFound", resourceCulture);
            }
        }
        
        public static string Web_Error_NoShareLoaded {
            get {
                return ResourceManager.GetString("Web_Error_NoShareLoaded", resourceCulture);
            }
        }
        
        public static string Web_Error_LoadFilesFailed {
            get {
                return ResourceManager.GetString("Web_Error_LoadFilesFailed", resourceCulture);
            }
        }
        
        public static string Web_Error_ShareExists {
            get {
                return ResourceManager.GetString("Web_Error_ShareExists", resourceCulture);
            }
        }
        
        public static string Web_Error_CreateShareFailed {
            get {
                return ResourceManager.GetString("Web_Error_CreateShareFailed", resourceCulture);
            }
        }
        
        public static string Web_Error_LoadSharesFailed {
            get {
                return ResourceManager.GetString("Web_Error_LoadSharesFailed", resourceCulture);
            }
        }
        
        public static string Web_Error_ChangeVisibilityFailed {
            get {
                return ResourceManager.GetString("Web_Error_ChangeVisibilityFailed", resourceCulture);
            }
        }
        
        public static string Web_Error_ChangeStatusFailed {
            get {
                return ResourceManager.GetString("Web_Error_ChangeStatusFailed", resourceCulture);
            }
        }
        
        public static string Web_Acl_LoadPermissionsFailed {
            get {
                return ResourceManager.GetString("Web_Acl_LoadPermissionsFailed", resourceCulture);
            }
        }
        
        public static string Web_Acl_Added {
            get {
                return ResourceManager.GetString("Web_Acl_Added", resourceCulture);
            }
        }
        
        public static string Web_Acl_Updated {
            get {
                return ResourceManager.GetString("Web_Acl_Updated", resourceCulture);
            }
        }
        
        public static string Web_Acl_Removed {
            get {
                return ResourceManager.GetString("Web_Acl_Removed", resourceCulture);
            }
        }
        
        public static string Web_Acl_SelectAtLeastOnePermission {
            get {
                return ResourceManager.GetString("Web_Acl_SelectAtLeastOnePermission", resourceCulture);
            }
        }
        
        public static string Web_Error_SelectUserOrGroup {
            get {
                return ResourceManager.GetString("Web_Error_SelectUserOrGroup", resourceCulture);
            }
        }
        
        public static string Web_Error_AddFailed {
            get {
                return ResourceManager.GetString("Web_Error_AddFailed", resourceCulture);
            }
        }
        
        public static string Web_Error_SaveFailed {
            get {
                return ResourceManager.GetString("Web_Error_SaveFailed", resourceCulture);
            }
        }
        
        public static string Web_Error_RemoveFailed {
            get {
                return ResourceManager.GetString("Web_Error_RemoveFailed", resourceCulture);
            }
        }
        
        public static string Web_Error_CreateFailed {
            get {
                return ResourceManager.GetString("Web_Error_CreateFailed", resourceCulture);
            }
        }
        
        public static string Web_Error_LoadFailedGeneric {
            get {
                return ResourceManager.GetString("Web_Error_LoadFailedGeneric", resourceCulture);
            }
        }
        
        public static string Web_Error_EntryNotFound {
            get {
                return ResourceManager.GetString("Web_Error_EntryNotFound", resourceCulture);
            }
        }
        
        public static string Web_Error_NameRequired {
            get {
                return ResourceManager.GetString("Web_Error_NameRequired", resourceCulture);
            }
        }
        
        public static string Web_ChangesSaved {
            get {
                return ResourceManager.GetString("Web_ChangesSaved", resourceCulture);
            }
        }
        
        public static string Web_Dept_Created {
            get {
                return ResourceManager.GetString("Web_Dept_Created", resourceCulture);
            }
        }
        
        public static string Web_Dept_Deleted {
            get {
                return ResourceManager.GetString("Web_Dept_Deleted", resourceCulture);
            }
        }
        
        public static string Web_Dept_Saved {
            get {
                return ResourceManager.GetString("Web_Dept_Saved", resourceCulture);
            }
        }
        
        public static string Web_Dept_NameRequired {
            get {
                return ResourceManager.GetString("Web_Dept_NameRequired", resourceCulture);
            }
        }
        
        public static string Web_Dept_SelectDepartment {
            get {
                return ResourceManager.GetString("Web_Dept_SelectDepartment", resourceCulture);
            }
        }
        
        public static string Web_Dept_CannotDeleteGlobal {
            get {
                return ResourceManager.GetString("Web_Dept_CannotDeleteGlobal", resourceCulture);
            }
        }
        
        public static string Web_Dept_NoPermissionInDept {
            get {
                return ResourceManager.GetString("Web_Dept_NoPermissionInDept", resourceCulture);
            }
        }
        
        public static string Web_Dept_NoPermissionEdit {
            get {
                return ResourceManager.GetString("Web_Dept_NoPermissionEdit", resourceCulture);
            }
        }
        
        public static string Web_User_Created {
            get {
                return ResourceManager.GetString("Web_User_Created", resourceCulture);
            }
        }
        
        public static string Web_User_Deleted {
            get {
                return ResourceManager.GetString("Web_User_Deleted", resourceCulture);
            }
        }
        
        public static string Web_User_NameTaken {
            get {
                return ResourceManager.GetString("Web_User_NameTaken", resourceCulture);
            }
        }
        
        public static string Web_User_NameRequired {
            get {
                return ResourceManager.GetString("Web_User_NameRequired", resourceCulture);
            }
        }
        
        public static string Web_User_NoPermissionEdit {
            get {
                return ResourceManager.GetString("Web_User_NoPermissionEdit", resourceCulture);
            }
        }
        
        public static string Web_User_NoPermissionPasswordReset {
            get {
                return ResourceManager.GetString("Web_User_NoPermissionPasswordReset", resourceCulture);
            }
        }
        
        public static string Web_User_PasswordMinLength {
            get {
                return ResourceManager.GetString("Web_User_PasswordMinLength", resourceCulture);
            }
        }
        
        public static string Web_User_PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("Web_User_PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        public static string Web_Group_Created {
            get {
                return ResourceManager.GetString("Web_Group_Created", resourceCulture);
            }
        }
        
        public static string Web_Group_Deleted {
            get {
                return ResourceManager.GetString("Web_Group_Deleted", resourceCulture);
            }
        }
        
        public static string Web_Group_NameRequired {
            get {
                return ResourceManager.GetString("Web_Group_NameRequired", resourceCulture);
            }
        }
        
        public static string Web_Role_Created {
            get {
                return ResourceManager.GetString("Web_Role_Created", resourceCulture);
            }
        }
        
        public static string Web_Role_Deleted {
            get {
                return ResourceManager.GetString("Web_Role_Deleted", resourceCulture);
            }
        }
        
        public static string Web_Role_Saved {
            get {
                return ResourceManager.GetString("Web_Role_Saved", resourceCulture);
            }
        }
        
        public static string Web_Role_NameRequired {
            get {
                return ResourceManager.GetString("Web_Role_NameRequired", resourceCulture);
            }
        }
        
        public static string Web_Scope_SelectScope {
            get {
                return ResourceManager.GetString("Web_Scope_SelectScope", resourceCulture);
            }
        }
        
        public static string Web_Error_LoadAccessRightsFailed {
            get {
                return ResourceManager.GetString("Web_Error_LoadAccessRightsFailed", resourceCulture);
            }
        }
        
        public static string Web_Error_GrantAccessFailed {
            get {
                return ResourceManager.GetString("Web_Error_GrantAccessFailed", resourceCulture);
            }
        }
        
        public static string Web_Error_RevokeAccessFailed {
            get {
                return ResourceManager.GetString("Web_Error_RevokeAccessFailed", resourceCulture);
            }
        }
        
        public static string Web_Error_CreateAssignmentFailed {
            get {
                return ResourceManager.GetString("Web_Error_CreateAssignmentFailed", resourceCulture);
            }
        }
        
        public static string Web_Error_DeleteAssignmentFailed {
            get {
                return ResourceManager.GetString("Web_Error_DeleteAssignmentFailed", resourceCulture);
            }
        }
        
        public static string Web_Assignment_Removed {
            get {
                return ResourceManager.GetString("Web_Assignment_Removed", resourceCulture);
            }
        }
        
        public static string Web_Assignment_Created {
            get {
                return ResourceManager.GetString("Web_Assignment_Created", resourceCulture);
            }
        }
        
        public static string Web_Members_Saved {
            get {
                return ResourceManager.GetString("Web_Members_Saved", resourceCulture);
            }
        }
        
        public static string Web_Settings_LoadFailed {
            get {
                return ResourceManager.GetString("Web_Settings_LoadFailed", resourceCulture);
            }
        }
        
        public static string Web_Settings_NoPermissionChange {
            get {
                return ResourceManager.GetString("Web_Settings_NoPermissionChange", resourceCulture);
            }
        }
        
        public static string Web_Settings_LanguageSaved {
            get {
                return ResourceManager.GetString("Web_Settings_LanguageSaved", resourceCulture);
            }
        }
        
        public static string Web_Settings_LanguageSaveFailed {
            get {
                return ResourceManager.GetString("Web_Settings_LanguageSaveFailed", resourceCulture);
            }
        }
        
        public static string Web_Settings_NoPermissionDataServices {
            get {
                return ResourceManager.GetString("Web_Settings_NoPermissionDataServices", resourceCulture);
            }
        }
        
        public static string Web_Settings_DataServiceSaveFailed {
            get {
                return ResourceManager.GetString("Web_Settings_DataServiceSaveFailed", resourceCulture);
            }
        }
        
        public static string Web_Settings_SmbEnabled {
            get {
                return ResourceManager.GetString("Web_Settings_SmbEnabled", resourceCulture);
            }
        }
        
        public static string Web_Settings_SmbDisabled {
            get {
                return ResourceManager.GetString("Web_Settings_SmbDisabled", resourceCulture);
            }
        }

        public static string Web_Settings_ContextMenu {
            get {
                return ResourceManager.GetString("Web_Settings_ContextMenu", resourceCulture);
            }
        }

        public static string Web_Settings_ContextMenu_Desc {
            get {
                return ResourceManager.GetString("Web_Settings_ContextMenu_Desc", resourceCulture);
            }
        }

        public static string Web_Settings_CtxAvailable {
            get {
                return ResourceManager.GetString("Web_Settings_CtxAvailable", resourceCulture);
            }
        }

        public static string Web_Settings_CtxAssigned {
            get {
                return ResourceManager.GetString("Web_Settings_CtxAssigned", resourceCulture);
            }
        }

        public static string Web_Settings_CtxAdd {
            get {
                return ResourceManager.GetString("Web_Settings_CtxAdd", resourceCulture);
            }
        }

        public static string Web_Settings_CtxRemove {
            get {
                return ResourceManager.GetString("Web_Settings_CtxRemove", resourceCulture);
            }
        }

        public static string Web_Settings_CtxMoveUp {
            get {
                return ResourceManager.GetString("Web_Settings_CtxMoveUp", resourceCulture);
            }
        }

        public static string Web_Settings_CtxMoveDown {
            get {
                return ResourceManager.GetString("Web_Settings_CtxMoveDown", resourceCulture);
            }
        }

        public static string Web_Settings_CtxReset {
            get {
                return ResourceManager.GetString("Web_Settings_CtxReset", resourceCulture);
            }
        }

        public static string Web_Settings_CtxSaved {
            get {
                return ResourceManager.GetString("Web_Settings_CtxSaved", resourceCulture);
            }
        }

        public static string Web_Settings_CtxSaveFailed {
            get {
                return ResourceManager.GetString("Web_Settings_CtxSaveFailed", resourceCulture);
            }
        }

        public static string Web_Settings_CtxScope_Background {
            get {
                return ResourceManager.GetString("Web_Settings_CtxScope_Background", resourceCulture);
            }
        }

        public static string Web_Settings_CtxScope_Folder {
            get {
                return ResourceManager.GetString("Web_Settings_CtxScope_Folder", resourceCulture);
            }
        }

        public static string Web_Settings_CtxScope_Archive {
            get {
                return ResourceManager.GetString("Web_Settings_CtxScope_Archive", resourceCulture);
            }
        }

        public static string Web_Settings_CtxScope_Image {
            get {
                return ResourceManager.GetString("Web_Settings_CtxScope_Image", resourceCulture);
            }
        }

        public static string Web_Settings_CtxScope_Video {
            get {
                return ResourceManager.GetString("Web_Settings_CtxScope_Video", resourceCulture);
            }
        }

        public static string Web_Settings_CtxScope_Audio {
            get {
                return ResourceManager.GetString("Web_Settings_CtxScope_Audio", resourceCulture);
            }
        }

        public static string Web_Settings_CtxScope_Document {
            get {
                return ResourceManager.GetString("Web_Settings_CtxScope_Document", resourceCulture);
            }
        }

        public static string Web_Settings_CtxScope_OtherFile {
            get {
                return ResourceManager.GetString("Web_Settings_CtxScope_OtherFile", resourceCulture);
            }
        }

        public static string Web_Settings_CtxScope_Multi {
            get {
                return ResourceManager.GetString("Web_Settings_CtxScope_Multi", resourceCulture);
            }
        }

        public static string Web_Validation_NameEmpty {
            get {
                return ResourceManager.GetString("Web_Validation_NameEmpty", resourceCulture);
            }
        }
        
        public static string Web_ShareName_MaxLength {
            get {
                return ResourceManager.GetString("Web_ShareName_MaxLength", resourceCulture);
            }
        }
        
        public static string Web_ShareName_AllowedChars {
            get {
                return ResourceManager.GetString("Web_ShareName_AllowedChars", resourceCulture);
            }
        }
        
        public static string Web_ShareName_NoLeadingTrailingDot {
            get {
                return ResourceManager.GetString("Web_ShareName_NoLeadingTrailingDot", resourceCulture);
            }
        }
        
        public static string Web_Share_RenamedTo {
            get {
                return ResourceManager.GetString("Web_Share_RenamedTo", resourceCulture);
            }
        }
        
        public static string Web_Share_RecycleEnabled {
            get {
                return ResourceManager.GetString("Web_Share_RecycleEnabled", resourceCulture);
            }
        }
        
        public static string Web_Share_RecycleDisabled {
            get {
                return ResourceManager.GetString("Web_Share_RecycleDisabled", resourceCulture);
            }
        }
        
        public static string Web_Error_ArchiveExists {
            get {
                return ResourceManager.GetString("Web_Error_ArchiveExists", resourceCulture);
            }
        }
        
        public static string Web_Validation_NameWhitespace {
            get {
                return ResourceManager.GetString("Web_Validation_NameWhitespace", resourceCulture);
            }
        }
        
        public static string Web_Validation_NameTooLong {
            get {
                return ResourceManager.GetString("Web_Validation_NameTooLong", resourceCulture);
            }
        }
        
        public static string Web_Validation_InvalidChars {
            get {
                return ResourceManager.GetString("Web_Validation_InvalidChars", resourceCulture);
            }
        }
        
        public static string Web_Validation_NameEndsWithDot {
            get {
                return ResourceManager.GetString("Web_Validation_NameEndsWithDot", resourceCulture);
            }
        }
        
        public static string Web_Validation_NameEndsWithSpace {
            get {
                return ResourceManager.GetString("Web_Validation_NameEndsWithSpace", resourceCulture);
            }
        }
        
        public static string Web_Validation_ReservedName {
            get {
                return ResourceManager.GetString("Web_Validation_ReservedName", resourceCulture);
            }
        }
        
        public static string Web_DeptPerm_Read {
            get {
                return ResourceManager.GetString("Web_DeptPerm_Read", resourceCulture);
            }
        }
        
        public static string Web_DeptPerm_ReadDesc {
            get {
                return ResourceManager.GetString("Web_DeptPerm_ReadDesc", resourceCulture);
            }
        }
        
        public static string Web_DeptPerm_Write {
            get {
                return ResourceManager.GetString("Web_DeptPerm_Write", resourceCulture);
            }
        }
        
        public static string Web_DeptPerm_WriteDesc {
            get {
                return ResourceManager.GetString("Web_DeptPerm_WriteDesc", resourceCulture);
            }
        }
        
        public static string Web_DeptPerm_Delete {
            get {
                return ResourceManager.GetString("Web_DeptPerm_Delete", resourceCulture);
            }
        }
        
        public static string Web_DeptPerm_DeleteDesc {
            get {
                return ResourceManager.GetString("Web_DeptPerm_DeleteDesc", resourceCulture);
            }
        }
        
        public static string Web_DeptPerm_Admin {
            get {
                return ResourceManager.GetString("Web_DeptPerm_Admin", resourceCulture);
            }
        }
        
        public static string Web_DeptPerm_AdminDesc {
            get {
                return ResourceManager.GetString("Web_DeptPerm_AdminDesc", resourceCulture);
            }
        }
        
        public static string Web_PermGroup_UserMgmt {
            get {
                return ResourceManager.GetString("Web_PermGroup_UserMgmt", resourceCulture);
            }
        }
        
        public static string Web_PermGroup_GroupMgmt {
            get {
                return ResourceManager.GetString("Web_PermGroup_GroupMgmt", resourceCulture);
            }
        }
        
        public static string Web_PermGroup_AssignDelegation {
            get {
                return ResourceManager.GetString("Web_PermGroup_AssignDelegation", resourceCulture);
            }
        }
        
        public static string Web_PermGroup_ShareMgmt {
            get {
                return ResourceManager.GetString("Web_PermGroup_ShareMgmt", resourceCulture);
            }
        }
        
        public static string Web_PermGroup_DeptMgmt {
            get {
                return ResourceManager.GetString("Web_PermGroup_DeptMgmt", resourceCulture);
            }
        }
        
        public static string Web_PermGroup_SystemMgmt {
            get {
                return ResourceManager.GetString("Web_PermGroup_SystemMgmt", resourceCulture);
            }
        }
        
        public static string Web_Perm_CreateUsers {
            get {
                return ResourceManager.GetString("Web_Perm_CreateUsers", resourceCulture);
            }
        }
        
        public static string Web_Perm_DeleteUsers {
            get {
                return ResourceManager.GetString("Web_Perm_DeleteUsers", resourceCulture);
            }
        }
        
        public static string Web_Perm_EditProfiles {
            get {
                return ResourceManager.GetString("Web_Perm_EditProfiles", resourceCulture);
            }
        }
        
        public static string Web_Perm_ResetPasswords {
            get {
                return ResourceManager.GetString("Web_Perm_ResetPasswords", resourceCulture);
            }
        }
        
        public static string Web_Perm_EnableDisable {
            get {
                return ResourceManager.GetString("Web_Perm_EnableDisable", resourceCulture);
            }
        }
        
        public static string Web_Perm_CreateGroups {
            get {
                return ResourceManager.GetString("Web_Perm_CreateGroups", resourceCulture);
            }
        }
        
        public static string Web_Perm_DeleteGroups {
            get {
                return ResourceManager.GetString("Web_Perm_DeleteGroups", resourceCulture);
            }
        }
        
        public static string Web_Perm_ManageMembers {
            get {
                return ResourceManager.GetString("Web_Perm_ManageMembers", resourceCulture);
            }
        }
        
        public static string Web_Perm_AssignGroups {
            get {
                return ResourceManager.GetString("Web_Perm_AssignGroups", resourceCulture);
            }
        }
        
        public static string Web_Perm_AssignRoles {
            get {
                return ResourceManager.GetString("Web_Perm_AssignRoles", resourceCulture);
            }
        }
        
        public static string Web_Perm_AssignDepartments {
            get {
                return ResourceManager.GetString("Web_Perm_AssignDepartments", resourceCulture);
            }
        }
        
        public static string Web_Perm_CreateShares {
            get {
                return ResourceManager.GetString("Web_Perm_CreateShares", resourceCulture);
            }
        }
        
        public static string Web_Perm_DeleteShares {
            get {
                return ResourceManager.GetString("Web_Perm_DeleteShares", resourceCulture);
            }
        }
        
        public static string Web_Perm_EditSettings {
            get {
                return ResourceManager.GetString("Web_Perm_EditSettings", resourceCulture);
            }
        }
        
        public static string Web_Perm_ManageAccess {
            get {
                return ResourceManager.GetString("Web_Perm_ManageAccess", resourceCulture);
            }
        }
        
        public static string Web_Perm_ManageAcls {
            get {
                return ResourceManager.GetString("Web_Perm_ManageAcls", resourceCulture);
            }
        }
        
        public static string Web_Perm_EditDepartment {
            get {
                return ResourceManager.GetString("Web_Perm_EditDepartment", resourceCulture);
            }
        }
        
        public static string Web_Perm_ViewDepartment {
            get {
                return ResourceManager.GetString("Web_Perm_ViewDepartment", resourceCulture);
            }
        }
        
        public static string Web_Perm_ManageSystemSettings {
            get {
                return ResourceManager.GetString("Web_Perm_ManageSystemSettings", resourceCulture);
            }
        }
        
        public static string Web_Perm_ManageDataServices {
            get {
                return ResourceManager.GetString("Web_Perm_ManageDataServices", resourceCulture);
            }
        }
        
        public static string Web_Share_Enabled {
            get {
                return ResourceManager.GetString("Web_Share_Enabled", resourceCulture);
            }
        }
        
        public static string Web_Share_Disabled {
            get {
                return ResourceManager.GetString("Web_Share_Disabled", resourceCulture);
            }
        }
        
        public static string Web_Tab_UsersCount {
            get {
                return ResourceManager.GetString("Web_Tab_UsersCount", resourceCulture);
            }
        }
        
        public static string Web_Tab_GroupsCount {
            get {
                return ResourceManager.GetString("Web_Tab_GroupsCount", resourceCulture);
            }
        }
        
        public static string Web_Tab_RolesCount {
            get {
                return ResourceManager.GetString("Web_Tab_RolesCount", resourceCulture);
            }
        }

        public static string Web_Settings_PwPolicy_TooShort {
            get {
                return ResourceManager.GetString("Web_Settings_PwPolicy_TooShort", resourceCulture);
            }
        }

        public static string Web_Settings_PwPolicy_NeedUpper {
            get {
                return ResourceManager.GetString("Web_Settings_PwPolicy_NeedUpper", resourceCulture);
            }
        }

        public static string Web_Settings_PwPolicy_NeedLower {
            get {
                return ResourceManager.GetString("Web_Settings_PwPolicy_NeedLower", resourceCulture);
            }
        }

        public static string Web_Settings_PwPolicy_NeedDigit {
            get {
                return ResourceManager.GetString("Web_Settings_PwPolicy_NeedDigit", resourceCulture);
            }
        }

        public static string Web_Settings_PwPolicy_NeedSpecial {
            get {
                return ResourceManager.GetString("Web_Settings_PwPolicy_NeedSpecial", resourceCulture);
            }
        }

        public static string Web_Settings_PwPolicySaved {
            get {
                return ResourceManager.GetString("Web_Settings_PwPolicySaved", resourceCulture);
            }
        }

        public static string Web_Settings_PwPolicySaveFailed {
            get {
                return ResourceManager.GetString("Web_Settings_PwPolicySaveFailed", resourceCulture);
            }
        }
    }
}
