FROM alpine:3.22

RUN apk add --no-cache openssl

COPY generate-control-plane-certs.sh /usr/local/bin/generate-control-plane-certs
RUN chmod 755 /usr/local/bin/generate-control-plane-certs

ENTRYPOINT ["/usr/local/bin/generate-control-plane-certs", "/pki"]
