<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>Kaimo_File_Server.Web</RootNamespace>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>9573d0b4-8b32-4bb5-a949-9934a4f80f0d</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Kaimo_File_Server.Core\Kaimo_File_Server.Core.csproj" />
		<ProjectReference Include="..\Kaimo_File_Server.Infrastructure\Kaimo_File_Server.Infrastructure.csproj" />
	</ItemGroup>

	
	<ItemGroup>
	  <Folder Include="Components\Pages\" />
	  <Folder Include="Components\ViewModels\" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	
	<ItemGroup>
	  <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.18.0" />
	  <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
	  <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
	</ItemGroup>

</Project>
