#!/usr/bin/env python3
"""Generate LogEvents.cs, LogMessages.resx and LogMessages.Designer.cs from a TSV master.

TSV columns (tab separated), lines starting with '#' or blank are ignored:
    Name <TAB> EventId <TAB> Message

The EventId's thousands-digit selects the owning project region.
Message uses named structured-logging placeholders, e.g. "Share sync failed for {Share}".
"""
import sys, os, html, re

HERE = os.path.dirname(os.path.abspath(__file__))
TSV = os.path.join(HERE, "logmessages.tsv")
# tools/loggen -> repo root -> src/.../Core/Logging
OUT = os.path.normpath(os.path.join(
    HERE, "..", "..", "src", "Kaimo_File_Server.Core", "Logging"))

RANGES = [
    (1000, 1999, "Core"),
    (2000, 2999, "Infrastructure"),
    (3000, 3999, "Search"),
    (4000, 4999, "Smb"),
    (5000, 5999, "Web"),
    (6000, 6999, "Host"),
]

def region_for(eid):
    for lo, hi, name in RANGES:
        if lo <= eid <= hi:
            return name
    raise SystemExit(f"EventId {eid} out of defined ranges")

def load():
    rows = []
    seen_name, seen_id = {}, {}
    with open(TSV, encoding="utf-8") as f:
        for ln, raw in enumerate(f, 1):
            line = raw.rstrip("\n")
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) != 3:
                raise SystemExit(f"{TSV}:{ln}: expected 3 tab-separated columns, got {len(parts)}: {line!r}")
            name, eid, msg = parts[0].strip(), parts[1].strip(), parts[2]
            if not re.fullmatch(r"[A-Za-z][A-Za-z0-9]*", name):
                raise SystemExit(f"{TSV}:{ln}: invalid name {name!r}")
            eid = int(eid)
            if name in seen_name:
                raise SystemExit(f"{TSV}:{ln}: duplicate name {name!r} (first at line {seen_name[name]})")
            if eid in seen_id:
                raise SystemExit(f"{TSV}:{ln}: duplicate id {eid} (first at line {seen_id[eid]})")
            seen_name[name] = ln
            seen_id[eid] = ln
            rows.append((name, eid, msg))
    return rows

def gen_events(rows):
    by_region = {}
    for name, eid, msg in rows:
        by_region.setdefault(region_for(eid), []).append((eid, name))
    out = []
    out.append("// <auto-generated> — generated from logmessages master. Do not edit by hand;")
    out.append("// add entries to the log-message source and regenerate.")
    out.append("using Microsoft.Extensions.Logging;")
    out.append("")
    out.append("namespace Kaimo_File_Server.Core.Logging;")
    out.append("")
    out.append("/// <summary>")
    out.append("/// Central catalog of <see cref=\"EventId\"/> codes = the \"where did this come from\" map for logs.")
    out.append("/// Numeric ranges are assigned per project so a bare <c>[nnnn]</c> in a log line points straight")
    out.append("/// at the owning subsystem:")
    out.append("/// <list type=\"bullet\">")
    for lo, hi, name in RANGES:
        out.append(f"/// <item><c>{lo}-{hi}</c> — {name}</item>")
    out.append("/// </list>")
    out.append("/// Each event name matches a key in <see cref=\"LogMessages\"/> holding the English template.")
    out.append("/// </summary>")
    out.append("public static class LogEvents")
    out.append("{")
    first = True
    for lo, hi, region in RANGES:
        items = sorted(by_region.get(region, []))
        if not items:
            continue
        if not first:
            out.append("")
        first = False
        out.append(f"    #region {region} ({lo}-{hi})")
        out.append("")
        for eid, name in items:
            out.append(f"    public static readonly EventId {name} = new({eid}, nameof({name}));")
        out.append("")
        out.append("    #endregion")
    out.append("}")
    return "\n".join(out) + "\n"

RESX_HEADER = '''﻿<?xml version="1.0" encoding="utf-8"?>
<root>
  <!-- Generated file. English (invariant) log message templates. Do not localize. -->
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
'''

def gen_resx(rows):
    out = [RESX_HEADER]
    for name, eid, msg in rows:
        out.append(f'  <data name="{name}" xml:space="preserve">')
        out.append(f'    <value>{html.escape(msg, quote=False)}</value>')
        out.append('  </data>')
    out.append('</root>')
    return "\n".join(out) + "\n"

def gen_designer(rows):
    out = []
    out.append("//------------------------------------------------------------------------------")
    out.append("// <auto-generated>")
    out.append("//     Generated from LogMessages.resx. Do not edit by hand; regenerate instead.")
    out.append("// </auto-generated>")
    out.append("//------------------------------------------------------------------------------")
    out.append("")
    out.append("namespace Kaimo_File_Server.Core.Logging {")
    out.append("    using System;")
    out.append("")
    out.append("    /// <summary>")
    out.append("    ///   English (invariant) log message templates. Companion to <see cref=\"LogEvents\"/>.")
    out.append("    /// </summary>")
    out.append("    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"System.Resources.Tools.StronglyTypedResourceBuilder\", \"18.0.0.0\")]")
    out.append("    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]")
    out.append("    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]")
    out.append("    public class LogMessages {")
    out.append("")
    out.append("        private static global::System.Resources.ResourceManager resourceMan;")
    out.append("")
    out.append("        private static global::System.Globalization.CultureInfo resourceCulture;")
    out.append("")
    out.append("        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute(\"Microsoft.Performance\", \"CA1811:AvoidUncalledPrivateCode\")]")
    out.append("        internal LogMessages() {")
    out.append("        }")
    out.append("")
    out.append("        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]")
    out.append("        public static global::System.Resources.ResourceManager ResourceManager {")
    out.append("            get {")
    out.append("                if (object.ReferenceEquals(resourceMan, null)) {")
    out.append("                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(\"Kaimo_File_Server.Core.Logging.LogMessages\", typeof(LogMessages).Assembly);")
    out.append("                    resourceMan = temp;")
    out.append("                }")
    out.append("                return resourceMan;")
    out.append("            }")
    out.append("        }")
    out.append("")
    out.append("        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]")
    out.append("        public static global::System.Globalization.CultureInfo Culture {")
    out.append("            get {")
    out.append("                return resourceCulture;")
    out.append("            }")
    out.append("            set {")
    out.append("                resourceCulture = value;")
    out.append("            }")
    out.append("        }")
    for name, eid, msg in rows:
        summary = html.escape(msg, quote=False)
        out.append("")
        out.append("        /// <summary>")
        out.append(f"        ///   Looks up a localized string similar to {summary}.")
        out.append("        /// </summary>")
        out.append(f"        public static string {name} {{")
        out.append("            get {")
        out.append(f"                return ResourceManager.GetString(\"{name}\", resourceCulture);")
        out.append("            }")
        out.append("        }")
    out.append("    }")
    out.append("}")
    return "\n".join(out) + "\n"

def main():
    rows = load()
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "LogEvents.cs"), "w", encoding="utf-8", newline="\r\n") as f:
        f.write(gen_events(rows))
    with open(os.path.join(OUT, "LogMessages.resx"), "w", encoding="utf-8", newline="\r\n") as f:
        f.write(gen_resx(rows))
    with open(os.path.join(OUT, "LogMessages.Designer.cs"), "w", encoding="utf-8", newline="\r\n") as f:
        f.write(gen_designer(rows))
    print(f"Generated {len(rows)} log messages -> {OUT}")

if __name__ == "__main__":
    main()
