<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Kaimo_File_Server_Core-7e70b808-b483-4fb9-9d04-597f4fa0cd3a</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
	<DockerComposeProjectPath>..\..\docker-compose.dcproj</DockerComposeProjectPath>
    <RootNamespace>Kaimo_File_Server</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Tasks.Git">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kaimo_File_Server.Core\Kaimo_File_Server.Core.csproj" />
    <ProjectReference Include="..\Kaimo_File_Server.Infrastructure\Kaimo_File_Server.Infrastructure.csproj" />
    <ProjectReference Include="..\Kaimo_File_Server.Search\Kaimo_File_Server.Search.csproj" />
  </ItemGroup>

</Project>
