// <auto-generated> — generated from logmessages master. Do not edit by hand;
// add entries to the log-message source and regenerate.
using Microsoft.Extensions.Logging;

namespace Kaimo_File_Server.Core.Logging;

/// <summary>
/// Central catalog of <see cref="EventId"/> codes = the "where did this come from" map for logs.
/// Numeric ranges are assigned per project so a bare <c>[nnnn]</c> in a log line points straight
/// at the owning subsystem:
/// <list type="bullet">
/// <item><c>1000-1999</c> — Core</item>
/// <item><c>2000-2999</c> — Infrastructure</item>
/// <item><c>3000-3999</c> — Search</item>
/// <item><c>4000-4999</c> — Smb</item>
/// <item><c>5000-5999</c> — Web</item>
/// <item><c>6000-6999</c> — Host</item>
/// </list>
/// Each event name matches a key in <see cref="LogMessages"/> holding the English template.
/// </summary>
public static class LogEvents
{
    #region Core (1000-1999)

    public static readonly EventId FileVersionSnapshotFailed = new(1001, nameof(FileVersionSnapshotFailed));
    public static readonly EventId FileSearchHookFailed = new(1002, nameof(FileSearchHookFailed));
    public static readonly EventId FileOwnerRecordFailed = new(1003, nameof(FileOwnerRecordFailed));
    public static readonly EventId FileWriteVersionFailed = new(1004, nameof(FileWriteVersionFailed));
    public static readonly EventId FileVersionCreated = new(1101, nameof(FileVersionCreated));

    #endregion

    #region Infrastructure (2000-2999)

    public static readonly EventId StorageAclLoadFailed = new(2001, nameof(StorageAclLoadFailed));
    public static readonly EventId SeedBootstrapAdminSkipped = new(2101, nameof(SeedBootstrapAdminSkipped));
    public static readonly EventId SeedAdminRoleMissing = new(2102, nameof(SeedAdminRoleMissing));
    public static readonly EventId SeedBootstrapAdminPassword = new(2103, nameof(SeedBootstrapAdminPassword));
    public static readonly EventId SeedBootstrapAdminCreated = new(2104, nameof(SeedBootstrapAdminCreated));
    public static readonly EventId SeedGlobalDepartmentCreated = new(2105, nameof(SeedGlobalDepartmentCreated));
    public static readonly EventId SeedRoleUpdated = new(2106, nameof(SeedRoleUpdated));
    public static readonly EventId SeedRoleCreated = new(2107, nameof(SeedRoleCreated));
    public static readonly EventId SeedGroupCreated = new(2108, nameof(SeedGroupCreated));
    public static readonly EventId SeedDepartmentsCreated = new(2109, nameof(SeedDepartmentsCreated));
    public static readonly EventId SeedTestUsersSkipped = new(2110, nameof(SeedTestUsersSkipped));
    public static readonly EventId SeedTestUsersCreating = new(2111, nameof(SeedTestUsersCreating));
    public static readonly EventId SeedConfigEntries = new(2112, nameof(SeedConfigEntries));
    public static readonly EventId SeedTestUserSummary = new(2113, nameof(SeedTestUserSummary));
    public static readonly EventId SeedDuplicateRolesRemoved = new(2114, nameof(SeedDuplicateRolesRemoved));
    public static readonly EventId SeedDuplicateGroupsRemoved = new(2115, nameof(SeedDuplicateGroupsRemoved));
    public static readonly EventId DatabaseReady = new(2201, nameof(DatabaseReady));
    public static readonly EventId DatabaseNotReadyRetry = new(2202, nameof(DatabaseNotReadyRetry));
    public static readonly EventId LogLevelApplied = new(2301, nameof(LogLevelApplied));
    public static readonly EventId LogLevelReloadFailed = new(2302, nameof(LogLevelReloadFailed));

    #endregion

    #region Search (3000-3999)

    public static readonly EventId SearchFlagReadFailed = new(3201, nameof(SearchFlagReadFailed));
    public static readonly EventId SearchElasticFailed = new(3202, nameof(SearchElasticFailed));
    public static readonly EventId SearchElasticUnreachable = new(3203, nameof(SearchElasticUnreachable));
    public static readonly EventId SearchElasticDisabled = new(3204, nameof(SearchElasticDisabled));
    public static readonly EventId SearchReindexFailed = new(3205, nameof(SearchReindexFailed));

    #endregion

    #region Smb (4000-4999)

    public static readonly EventId SmbAlreadyRunning = new(4001, nameof(SmbAlreadyRunning));
    public static readonly EventId SmbNotRunning = new(4002, nameof(SmbNotRunning));
    public static readonly EventId SmbStopped = new(4003, nameof(SmbStopped));
    public static readonly EventId SmbLibraryMessage = new(4004, nameof(SmbLibraryMessage));
    public static readonly EventId SmbAuditEvent = new(4005, nameof(SmbAuditEvent));
    public static readonly EventId SmbStarted = new(4006, nameof(SmbStarted));
    public static readonly EventId SmbWatchingStorage = new(4007, nameof(SmbWatchingStorage));
    public static readonly EventId SmbShareLoaded = new(4101, nameof(SmbShareLoaded));
    public static readonly EventId SmbStorageChanged = new(4102, nameof(SmbStorageChanged));
    public static readonly EventId SmbSyncFailed = new(4103, nameof(SmbSyncFailed));
    public static readonly EventId SmbShareAlreadyExists = new(4104, nameof(SmbShareAlreadyExists));
    public static readonly EventId SmbShareAdded = new(4105, nameof(SmbShareAdded));
    public static readonly EventId SmbShareNotFound = new(4106, nameof(SmbShareNotFound));
    public static readonly EventId SmbShareRemoved = new(4107, nameof(SmbShareRemoved));
    public static readonly EventId SmbShareUpdated = new(4108, nameof(SmbShareUpdated));
    public static readonly EventId SmbShareRemovedSync = new(4109, nameof(SmbShareRemovedSync));
    public static readonly EventId SmbShareUpdatedSync = new(4110, nameof(SmbShareUpdatedSync));
    public static readonly EventId SmbShareAddedSync = new(4111, nameof(SmbShareAddedSync));
    public static readonly EventId SmbSyncCompleted = new(4112, nameof(SmbSyncCompleted));
    public static readonly EventId SmbUserNotFound = new(4201, nameof(SmbUserNotFound));
    public static readonly EventId SmbNtHashLookupFailed = new(4202, nameof(SmbNtHashLookupFailed));
    public static readonly EventId SmbUserAuthenticated = new(4203, nameof(SmbUserAuthenticated));
    public static readonly EventId SmbVisibilityCheckFailed = new(4301, nameof(SmbVisibilityCheckFailed));
    public static readonly EventId SmbShareAccessCheckFailed = new(4302, nameof(SmbShareAccessCheckFailed));
    public static readonly EventId SmbCreateFailed = new(4401, nameof(SmbCreateFailed));
    public static readonly EventId SmbReadFailed = new(4402, nameof(SmbReadFailed));
    public static readonly EventId SmbWriteFailed = new(4403, nameof(SmbWriteFailed));
    public static readonly EventId SmbQueryDirectoryFailed = new(4404, nameof(SmbQueryDirectoryFailed));
    public static readonly EventId SmbSnapshotsFailed = new(4405, nameof(SmbSnapshotsFailed));
    public static readonly EventId SmbServiceStartFailed = new(4501, nameof(SmbServiceStartFailed));
    public static readonly EventId SmbServiceStopFailed = new(4502, nameof(SmbServiceStopFailed));
    public static readonly EventId SmbProtocolConfig = new(4601, nameof(SmbProtocolConfig));
    public static readonly EventId SmbProtocolLoadFailed = new(4602, nameof(SmbProtocolLoadFailed));
    public static readonly EventId SmbServerGuidLoadFailed = new(4603, nameof(SmbServerGuidLoadFailed));

    #endregion

    #region Web (5000-5999)

    public static readonly EventId AclEditorLoadData = new(5601, nameof(AclEditorLoadData));
    public static readonly EventId AclEditorNoPath = new(5602, nameof(AclEditorNoPath));
    public static readonly EventId AclEditorNoShareId = new(5603, nameof(AclEditorNoShareId));
    public static readonly EventId AclEditorLoading = new(5604, nameof(AclEditorLoading));
    public static readonly EventId AclEditorLoaded = new(5605, nameof(AclEditorLoaded));
    public static readonly EventId AclEditorLoadFailed = new(5606, nameof(AclEditorLoadFailed));
    public static readonly EventId AclEditorException = new(5607, nameof(AclEditorException));

    #endregion

    #region Host (6000-6999)

    public static readonly EventId ReconcilerStarted = new(6101, nameof(ReconcilerStarted));
    public static readonly EventId ReconcileRunFailed = new(6102, nameof(ReconcileRunFailed));
    public static readonly EventId ReconcileStopFailed = new(6103, nameof(ReconcileStopFailed));
    public static readonly EventId ServiceStarting = new(6104, nameof(ServiceStarting));
    public static readonly EventId ServiceStopping = new(6105, nameof(ServiceStopping));

    #endregion
}
