//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from LogMessages.resx. Do not edit by hand; regenerate instead.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaimo_File_Server.Core.Logging {
    using System;

    /// <summary>
    ///   English (invariant) log message templates. Companion to <see cref="LogEvents"/>.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogMessages {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kaimo_File_Server.Core.Logging.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SMB server already running, start skipped..
        /// </summary>
        public static string SmbAlreadyRunning {
            get {
                return ResourceManager.GetString("SmbAlreadyRunning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SMB server not running, stop skipped..
        /// </summary>
        public static string SmbNotRunning {
            get {
                return ResourceManager.GetString("SmbNotRunning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SMB server stopped..
        /// </summary>
        public static string SmbStopped {
            get {
                return ResourceManager.GetString("SmbStopped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {Message}.
        /// </summary>
        public static string SmbLibraryMessage {
            get {
                return ResourceManager.GetString("SmbLibraryMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SMB audit: {Event}.
        /// </summary>
        public static string SmbAuditEvent {
            get {
                return ResourceManager.GetString("SmbAuditEvent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SMB server started with {ShareCount} shares (ABE active)..
        /// </summary>
        public static string SmbStarted {
            get {
                return ResourceManager.GetString("SmbStarted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Watching storage folder: {Path}.
        /// </summary>
        public static string SmbWatchingStorage {
            get {
                return ResourceManager.GetString("SmbWatchingStorage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share loaded: {Share} ({ShareId}) -&gt; {Path}.
        /// </summary>
        public static string SmbShareLoaded {
            get {
                return ResourceManager.GetString("SmbShareLoaded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Storage change detected ({Reason}), synchronizing shares..
        /// </summary>
        public static string SmbStorageChanged {
            get {
                return ResourceManager.GetString("SmbStorageChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share sync from database failed..
        /// </summary>
        public static string SmbSyncFailed {
            get {
                return ResourceManager.GetString("SmbSyncFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share already exists, skipped: {Share}.
        /// </summary>
        public static string SmbShareAlreadyExists {
            get {
                return ResourceManager.GetString("SmbShareAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share added at runtime: {Share} ({ShareId}) -&gt; {Path}.
        /// </summary>
        public static string SmbShareAdded {
            get {
                return ResourceManager.GetString("SmbShareAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share not found, skipped: {Share}.
        /// </summary>
        public static string SmbShareNotFound {
            get {
                return ResourceManager.GetString("SmbShareNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share removed at runtime: {Share} ({ShareId}).
        /// </summary>
        public static string SmbShareRemoved {
            get {
                return ResourceManager.GetString("SmbShareRemoved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share updated: {OldName} -&gt; {NewName} ({ShareId}) -&gt; {Path}.
        /// </summary>
        public static string SmbShareUpdated {
            get {
                return ResourceManager.GetString("SmbShareUpdated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share removed during sync: {Share} ({ShareId}).
        /// </summary>
        public static string SmbShareRemovedSync {
            get {
                return ResourceManager.GetString("SmbShareRemovedSync", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share updated during sync: {Share} -&gt; {Path}.
        /// </summary>
        public static string SmbShareUpdatedSync {
            get {
                return ResourceManager.GetString("SmbShareUpdatedSync", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share added during sync: {Share} ({ShareId}) -&gt; {Path}.
        /// </summary>
        public static string SmbShareAddedSync {
            get {
                return ResourceManager.GetString("SmbShareAddedSync", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Database sync complete: {ShareCount} active shares..
        /// </summary>
        public static string SmbSyncCompleted {
            get {
                return ResourceManager.GetString("SmbSyncCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SMB auth: user not found: {User}.
        /// </summary>
        public static string SmbUserNotFound {
            get {
                return ResourceManager.GetString("SmbUserNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SMB auth: failed to retrieve NT hash for {User}..
        /// </summary>
        public static string SmbNtHashLookupFailed {
            get {
                return ResourceManager.GetString("SmbNtHashLookupFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SMB auth: user authenticated: {User}.
        /// </summary>
        public static string SmbUserAuthenticated {
            get {
                return ResourceManager.GetString("SmbUserAuthenticated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SMB ABE visibility check failed for share {Share}..
        /// </summary>
        public static string SmbVisibilityCheckFailed {
            get {
                return ResourceManager.GetString("SmbVisibilityCheckFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SMB share access check failed: {User} -&gt; {Share}..
        /// </summary>
        public static string SmbShareAccessCheckFailed {
            get {
                return ResourceManager.GetString("SmbShareAccessCheckFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SMB create failed for {Path}..
        /// </summary>
        public static string SmbCreateFailed {
            get {
                return ResourceManager.GetString("SmbCreateFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SMB read failed..
        /// </summary>
        public static string SmbReadFailed {
            get {
                return ResourceManager.GetString("SmbReadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SMB write failed..
        /// </summary>
        public static string SmbWriteFailed {
            get {
                return ResourceManager.GetString("SmbWriteFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SMB directory query failed..
        /// </summary>
        public static string SmbQueryDirectoryFailed {
            get {
                return ResourceManager.GetString("SmbQueryDirectoryFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SMB snapshot enumeration failed..
        /// </summary>
        public static string SmbSnapshotsFailed {
            get {
                return ResourceManager.GetString("SmbSnapshotsFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SMB service start failed..
        /// </summary>
        public static string SmbServiceStartFailed {
            get {
                return ResourceManager.GetString("SmbServiceStartFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SMB service stop failed..
        /// </summary>
        public static string SmbServiceStopFailed {
            get {
                return ResourceManager.GetString("SmbServiceStopFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SMB protocol {MinVersion}..{MaxVersion}, Signing={Signing}, Encryption={Encryption}, WsDiscovery={WsDiscovery}, Audit={Audit}, ServerGuid={ServerGuid}.
        /// </summary>
        public static string SmbProtocolConfig {
            get {
                return ResourceManager.GetString("SmbProtocolConfig", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not load SMB protocol settings, using defaults..
        /// </summary>
        public static string SmbProtocolLoadFailed {
            get {
                return ResourceManager.GetString("SmbProtocolLoadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not load SMB server GUID, using a random one..
        /// </summary>
        public static string SmbServerGuidLoadFailed {
            get {
                return ResourceManager.GetString("SmbServerGuidLoadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Versioning failed while closing {Path}..
        /// </summary>
        public static string FileVersionSnapshotFailed {
            get {
                return ResourceManager.GetString("FileVersionSnapshotFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search index hook failed for {Path}..
        /// </summary>
        public static string FileSearchHookFailed {
            get {
                return ResourceManager.GetString("FileSearchHookFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to record owner for {Path}..
        /// </summary>
        public static string FileOwnerRecordFailed {
            get {
                return ResourceManager.GetString("FileOwnerRecordFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Versioning failed after writing {Path}..
        /// </summary>
        public static string FileWriteVersionFailed {
            get {
                return ResourceManager.GetString("FileWriteVersionFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created version {Version} for {Path} ({OriginalBytes} -&gt; {CompressedBytes} bytes, {Ratio} ratio)..
        /// </summary>
        public static string FileVersionCreated {
            get {
                return ResourceManager.GetString("FileVersionCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ACL load failed for {Path}..
        /// </summary>
        public static string StorageAclLoadFailed {
            get {
                return ResourceManager.GetString("StorageAclLoadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Database ready..
        /// </summary>
        public static string DatabaseReady {
            get {
                return ResourceManager.GetString("DatabaseReady", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Database not ready, retrying in 3s ({RemainingAttempts} attempts left)..
        /// </summary>
        public static string DatabaseNotReadyRetry {
            get {
                return ResourceManager.GetString("DatabaseNotReadyRetry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Global log level set to {Level}..
        /// </summary>
        public static string LogLevelApplied {
            get {
                return ResourceManager.GetString("LogLevelApplied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to reload the global log level from the config store..
        /// </summary>
        public static string LogLevelReloadFailed {
            get {
                return ResourceManager.GetString("LogLevelReloadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Users already present, skipping bootstrap admin..
        /// </summary>
        public static string SeedBootstrapAdminSkipped {
            get {
                return ResourceManager.GetString("SeedBootstrapAdminSkipped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Administrator role missing, cannot seed bootstrap admin..
        /// </summary>
        public static string SeedAdminRoleMissing {
            get {
                return ResourceManager.GetString("SeedAdminRoleMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bootstrap admin created (user 'admin'). Generated one-time password: {Password}. Change it immediately; this password will NOT be shown again..
        /// </summary>
        public static string SeedBootstrapAdminPassword {
            get {
                return ResourceManager.GetString("SeedBootstrapAdminPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bootstrap admin 'admin' created with the configured password..
        /// </summary>
        public static string SeedBootstrapAdminCreated {
            get {
                return ResourceManager.GetString("SeedBootstrapAdminCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Global department created (Id: {Id})..
        /// </summary>
        public static string SeedGlobalDepartmentCreated {
            get {
                return ResourceManager.GetString("SeedGlobalDepartmentCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Role '{Name}' updated -&gt; {Perms}.
        /// </summary>
        public static string SeedRoleUpdated {
            get {
                return ResourceManager.GetString("SeedRoleUpdated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Role '{Name}' created (permissions: {Perms}).
        /// </summary>
        public static string SeedRoleCreated {
            get {
                return ResourceManager.GetString("SeedRoleCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group '{Name}' created (department: Global).
        /// </summary>
        public static string SeedGroupCreated {
            get {
                return ResourceManager.GetString("SeedGroupCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Departments created: Entwicklung (-&gt; Backend, Frontend), Marketing, Geschaeftsleitung..
        /// </summary>
        public static string SeedDepartmentsCreated {
            get {
                return ResourceManager.GetString("SeedDepartmentsCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Users already present, skipping test users..
        /// </summary>
        public static string SeedTestUsersSkipped {
            get {
                return ResourceManager.GetString("SeedTestUsersSkipped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating test users....
        /// </summary>
        public static string SeedTestUsersCreating {
            get {
                return ResourceManager.GetString("SeedTestUsersCreating", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Config entries seeded..
        /// </summary>
        public static string SeedConfigEntries {
            get {
                return ResourceManager.GetString("SeedConfigEntries", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Test users created: admin, marco.hanisch, anna.weber, lisa.mueller (password '1234', admin 'admin1234')..
        /// </summary>
        public static string SeedTestUserSummary {
            get {
                return ResourceManager.GetString("SeedTestUserSummary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Removed {Count} duplicate role(s) named '{Name}'..
        /// </summary>
        public static string SeedDuplicateRolesRemoved {
            get {
                return ResourceManager.GetString("SeedDuplicateRolesRemoved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Removed {Count} duplicate group(s) named '{Name}'..
        /// </summary>
        public static string SeedDuplicateGroupsRemoved {
            get {
                return ResourceManager.GetString("SeedDuplicateGroupsRemoved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data service reconciler started ({Count} services)..
        /// </summary>
        public static string ReconcilerStarted {
            get {
                return ResourceManager.GetString("ReconcilerStarted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reconcile run failed..
        /// </summary>
        public static string ReconcileRunFailed {
            get {
                return ResourceManager.GetString("ReconcileRunFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to stop service '{Key}' during shutdown..
        /// </summary>
        public static string ReconcileStopFailed {
            get {
                return ResourceManager.GetString("ReconcileStopFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Starting data service '{Key}'..
        /// </summary>
        public static string ServiceStarting {
            get {
                return ResourceManager.GetString("ServiceStarting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stopping data service '{Key}'..
        /// </summary>
        public static string ServiceStopping {
            get {
                return ResourceManager.GetString("ServiceStopping", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not read the Elasticsearch flag, assuming enabled..
        /// </summary>
        public static string SearchFlagReadFailed {
            get {
                return ResourceManager.GetString("SearchFlagReadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Elasticsearch search failed, falling back to filename search..
        /// </summary>
        public static string SearchElasticFailed {
            get {
                return ResourceManager.GetString("SearchElasticFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Elasticsearch not reachable, search running in filename mode..
        /// </summary>
        public static string SearchElasticUnreachable {
            get {
                return ResourceManager.GetString("SearchElasticUnreachable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Elasticsearch disabled, search running in filename mode..
        /// </summary>
        public static string SearchElasticDisabled {
            get {
                return ResourceManager.GetString("SearchElasticDisabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reindex failed..
        /// </summary>
        public static string SearchReindexFailed {
            get {
                return ResourceManager.GetString("SearchReindexFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AclEditor.LoadDataAsync Path='{Path}', ShareId={ShareId}.
        /// </summary>
        public static string AclEditorLoadData {
            get {
                return ResourceManager.GetString("AclEditorLoadData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AclEditor: path is null, aborting..
        /// </summary>
        public static string AclEditorNoPath {
            get {
                return ResourceManager.GetString("AclEditorNoPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AclEditor: shareId is empty, aborting..
        /// </summary>
        public static string AclEditorNoShareId {
            get {
                return ResourceManager.GetString("AclEditorNoShareId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AclEditor: loading {Path} (share {ShareId}, isDirectory {IsDirectory})..
        /// </summary>
        public static string AclEditorLoading {
            get {
                return ResourceManager.GetString("AclEditorLoading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AclEditor: loaded={Loaded}, entries={Entries}, inherited={Inherited}..
        /// </summary>
        public static string AclEditorLoaded {
            get {
                return ResourceManager.GetString("AclEditorLoaded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AclEditor: load failed: {Error}.
        /// </summary>
        public static string AclEditorLoadFailed {
            get {
                return ResourceManager.GetString("AclEditorLoadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AclEditor: unhandled exception while loading ACL..
        /// </summary>
        public static string AclEditorException {
            get {
                return ResourceManager.GetString("AclEditorException", resourceCulture);
            }
        }
    }
}
